# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = ''
# Which is equivalent to
format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$direnv\
$custom\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncate_to_repo = false
truncation_length = 4

[directory.substitutions]
'/Users/collin/code/rippling-client/worktrees' = 'rr-wt'

[git_status]
style = 'cyan'
ignore_submodules = true

[hostname]
ssh_only = false
format = '[$hostname]($style) '

[character]
success_symbol = '[âžœ](bold green)'

