# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[git_status]
style = 'cyan'
ignore_submodules = true

[character]
success_symbol = '[âžœ](bold green)'

